site_name: Blueberry LLM Research
site_url: 
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    - content.tooltips
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
nav:
  - Home: index.md
  - Experiments: experiments.md
  - Usage: usage.md
  - Plots: plots.md
  - Research Guide: research_tutorial.md
  - Theory: theory.md
  - References: references.md
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
