from __future__ import annotations

import statistics
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import typer
from rich.console import Console
from typer import Context

from llm import MoEModelConfig

from experiments.logging_utils import append_row_csv
from experiments.run_scaling import build_config as build_scaling_config, parse_experts_list

from .config import DEFAULT_RUNS_DIR, ExperimentPaths, ExperimentRequest, WandbSettings, generate_experiment_id
from .deliverables import build_deliverable_summary
from .reporting import render_summary, save_training_curve, write_metrics, write_reports
from .runner import run_seed
from .storage import write_json
from .wizard import RunRequest, run_wizard

app = typer.Typer(help="Blueberry LLM experiment control center")
console = Console()


def _wandb_settings(
    project: Optional[str],
    entity: Optional[str],
    group: Optional[str],
    mode: Optional[str],
    tags: List[str],
) -> Optional[WandbSettings]:
    if not project:
        return None
    return WandbSettings(project=project, entity=entity, group=group, mode=mode, tags=tags)


def _build_config(**kwargs) -> MoEModelConfig:
    return MoEModelConfig(**kwargs)


@app.command()
def run(
    experiment_id: Optional[str] = typer.Option(None, help="Experiment identifier; autogenerated when omitted."),
    out_dir: Path = typer.Option(DEFAULT_RUNS_DIR, help="Directory to store experiment outputs."),
    seed: int = typer.Option(42, help="Base random seed."),
    num_seeds: int = typer.Option(1, min=1, help="Number of seed replicates to run."),
    # Model + training hyperparameters
    d_model: int = typer.Option(384, help="Model hidden size."),
    n_heads: int = typer.Option(8, help="Number of attention heads."),
    n_layers: int = typer.Option(6, help="Number of transformer layers."),
    d_ff: int = typer.Option(1536, help="Expert feed-forward width."),
    batch_size: int = typer.Option(24, help="Batch size."),
    max_steps: int = typer.Option(200, help="Training steps per run."),
    max_seq_len: int = typer.Option(512, help="Sequence length."),
    num_experts: int = typer.Option(8, help="Number of experts."),
    expert_top_k: int = typer.Option(2, help="Experts activated per token."),
    gradient_accumulation_steps: int = typer.Option(4, help="Gradient accumulation steps."),
    muon_lr: float = typer.Option(0.01, help="Muon optimizer base learning rate."),
    weight_decay: float = typer.Option(0.1, help="Weight decay."),
    dropout: float = typer.Option(0.1, help="Dropout probability."),
    eval_every: int = typer.Option(500, help="Steps between eval passes."),
    eval_steps: int = typer.Option(50, help="Validation steps."),
    collect_router_stats: bool = typer.Option(False, help="Collect router statistics during training."),
    save_checkpoint: bool = typer.Option(True, "--save-checkpoint/--no-save-checkpoint", help="Persist model checkpoint."),
    notes: Optional[str] = typer.Option(None, help="Free-form notes persisted alongside artifacts."),
    # wandb
    wandb_project: Optional[str] = typer.Option(None, help="Weights & Biases project name."),
    wandb_entity: Optional[str] = typer.Option(None, help="Weights & Biases entity/team."),
    wandb_group: Optional[str] = typer.Option(None, help="Weights & Biases group/tag for sweeps."),
    wandb_mode: Optional[str] = typer.Option(None, help="Weights & Biases mode (online/offline/run)."),
    tag: List[str] = typer.Option([], "--tag", help="Additional experiment tags."),
) -> None:
    """Run a single experiment (optionally across multiple seeds)."""

    experiment_id = experiment_id or generate_experiment_id("exp")
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    config = _build_config(
        d_model=d_model,
        n_heads=n_heads,
        n_layers=n_layers,
        d_ff=d_ff,
        batch_size=batch_size,
        max_steps=max_steps,
        max_seq_len=max_seq_len,
        num_experts=num_experts,
        expert_top_k=expert_top_k,
        gradient_accumulation_steps=gradient_accumulation_steps,
        muon_lr=muon_lr,
        weight_decay=weight_decay,
        dropout=dropout,
        eval_every=eval_every,
        eval_steps=eval_steps,
        collect_router_stats=collect_router_stats,
    )

    wandb_settings = _wandb_settings(wandb_project, wandb_entity, wandb_group, wandb_mode, tag)
    request = ExperimentRequest(
        experiment_id=experiment_id,
        base_config=config,
        output_root=out_dir,
        wandb=wandb_settings,
        notes=notes,
        tags=tag,
    )

    results = []
    console.print(f"🚀 Starting experiment {experiment_id} -> {out_dir}")

    for index in range(num_seeds):
        seed_value = seed + index
        replicate = index + 1 if num_seeds > 1 else None
        paths = request.build_run_directory(replicate=replicate)
        run_name = f"{experiment_id}-seed{seed_value}" if num_seeds > 1 else experiment_id
        console.print(f"• Running seed {seed_value} (outputs -> {paths.run_dir})")
        result = run_seed(
            request,
            seed_value=seed_value,
            wandb_settings=wandb_settings,
            paths=paths,
            run_name=run_name,
            tags=tag,
            notes=notes,
            save_checkpoint=save_checkpoint,
        )
        results.append((paths, result))

        metrics_path = write_metrics(result.metrics, paths.artifacts_dir / "metrics.json")
        history_path = paths.artifacts_dir / "train_history.json"
        eval_history_path = paths.artifacts_dir / "eval_history.json"
        summary_path = paths.artifacts_dir / "summary_events.json"
        write_json(history_path, result.train_history)
        write_json(eval_history_path, result.eval_history)
        write_json(summary_path, result.summary_events)
        curve_path = save_training_curve(result.train_history, paths.artifacts_dir / "training_curve.png")
        reports = write_reports(paths, result.metrics, notes)

        validation_results = {
            "all_deliverables_met": result.status == "completed" and metrics_path.exists(),
            "performance_targets_met": result.metrics.get("val_loss") is not None,
            "data_integrity_checks_passed": True,
        }

        deliverable = build_deliverable_summary(
            experiment_id=experiment_id,
            status=result.status,
            started_at=result.started_at,
            completed_at=result.completed_at,
            metrics=result.metrics,
            paths=paths,
            wandb_info=result.wandb_info,
            checkpoint_path=result.checkpoint_path,
            artifact_paths={
                "metrics": metrics_path,
                "training_curve": curve_path,
                "train_history": history_path,
                "eval_history": eval_history_path,
                "summary": summary_path,
            },
            report_paths=reports,
            validation_status=validation_results,
        )
        write_json(paths.run_dir / "deliverables.json", deliverable)
        render_summary(
            console,
            experiment_id=experiment_id,
            status=result.status,
            metrics=result.metrics,
            duration=result.duration,
            artifacts={
                "checkpoint": result.checkpoint_path,
                "metrics": metrics_path,
                "training_curve": curve_path,
            },
        )

    if num_seeds > 1:
        combined_metrics = {}
        for _, res in results:
            for key, value in res.metrics.items():
                if isinstance(value, (int, float)):
                    combined_metrics.setdefault(key, []).append(float(value))
        aggregated = {key: sum(values) / len(values) for key, values in combined_metrics.items() if values}
        root_paths = request.build_run_directory(replicate=None)
        aggregate_metrics_path = write_metrics(aggregated, root_paths.artifacts_dir / "aggregate_metrics.json")
        reports = write_reports(root_paths, aggregated, notes)
        status = "completed" if all(res.status == "completed" for _, res in results) else "partial_success"
        deliverable = build_deliverable_summary(
            experiment_id=experiment_id,
            status=status,
            started_at=results[0][1].started_at,
            completed_at=results[-1][1].completed_at,
            metrics=aggregated,
            paths=root_paths,
            wandb_info=None,
            checkpoint_path=None,
            artifact_paths={"aggregate_metrics": aggregate_metrics_path},
            report_paths=reports,
            validation_status={
                "all_deliverables_met": status == "completed",
                "performance_targets_met": bool(aggregated),
                "data_integrity_checks_passed": True,
            },
        )
        write_json(root_paths.run_dir / "deliverables.json", deliverable)
        render_summary(
            console,
            experiment_id=f"{experiment_id} (aggregate)",
            status=status,
            metrics=aggregated,
            duration=sum(res.duration for _, res in results),
            artifacts={"aggregate_metrics": aggregate_metrics_path},
        )


def _run_from_wizard(request: RunRequest) -> None:
    cfg = request.config
    run(
        experiment_id=request.experiment_id,
        out_dir=request.out_dir,
        seed=request.seed,
        num_seeds=request.num_seeds,
        d_model=cfg.d_model,
        n_heads=cfg.n_heads,
        n_layers=cfg.n_layers,
        d_ff=cfg.d_ff,
        batch_size=cfg.batch_size,
        max_steps=cfg.max_steps,
        max_seq_len=cfg.max_seq_len,
        num_experts=cfg.num_experts,
        expert_top_k=cfg.expert_top_k,
        gradient_accumulation_steps=cfg.gradient_accumulation_steps,
        muon_lr=cfg.muon_lr,
        weight_decay=cfg.weight_decay,
        dropout=cfg.dropout,
        eval_every=cfg.eval_every,
        eval_steps=cfg.eval_steps,
        collect_router_stats=getattr(cfg, "collect_router_stats", False),
        save_checkpoint=request.save_checkpoint,
        notes=request.notes,
        wandb_project=request.wandb_project,
        wandb_entity=request.wandb_entity,
        wandb_group=request.wandb_group,
        wandb_mode=request.wandb_mode,
        tag=request.tags,
    )


@app.command()
def grid(
    experiment_id: Optional[str] = typer.Option(None, help="Grid identifier; autogenerated when omitted."),
    out_dir: Path = typer.Option(DEFAULT_RUNS_DIR, help="Directory to store grid outputs."),
    regime: str = typer.Option("flops", help="Scaling regime (flops or params)."),
    experts: str = typer.Option("1,2,4,8,16", help="Comma-separated expert counts."),
    top_k: int = typer.Option(2, help="Experts activated per token."),
    d_model: int = typer.Option(384, help="Model hidden size."),
    n_heads: int = typer.Option(8, help="Number of attention heads."),
    n_layers: int = typer.Option(6, help="Number of transformer layers."),
    d_ff_dense: int = typer.Option(1536, help="Dense FFN width used as reference."),
    seq_len: int = typer.Option(512, help="Sequence length."),
    batch_size: int = typer.Option(16, help="Batch size per run."),
    max_steps: int = typer.Option(200, help="Training steps per run."),
    eval_steps: int = typer.Option(50, help="Validation steps per run."),
    seed: int = typer.Option(42, help="Base seed for replicates."),
    seeds: int = typer.Option(1, min=1, help="Number of seeds per configuration."),
    collect_router_stats: bool = typer.Option(False, help="Collect router diagnostics."),
    save_checkpoint: bool = typer.Option(False, "--save-checkpoint/--no-save-checkpoint", help="Persist checkpoints for each run."),
    notes: Optional[str] = typer.Option(None, help="Free-form notes persisted alongside artifacts."),
    wandb_project: Optional[str] = typer.Option(None, help="Weights & Biases project name."),
    wandb_entity: Optional[str] = typer.Option(None, help="Weights & Biases entity/team."),
    wandb_group: Optional[str] = typer.Option(None, help="Weights & Biases group/tag for sweeps."),
    wandb_mode: Optional[str] = typer.Option(None, help="Weights & Biases mode (online/offline/run)."),
    tag: List[str] = typer.Option([], "--tag", help="Additional experiment tags."),
) -> None:
    """Run a scaling grid inspired by the evalthai tool."""

    experiment_id = experiment_id or generate_experiment_id("grid")
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    expert_values = parse_experts_list(experts)
    if not expert_values:
        raise typer.BadParameter("No expert counts provided; use e.g. --experts 1,2,4,8")

    wandb_settings = _wandb_settings(wandb_project, wandb_entity, wandb_group, wandb_mode, tag)
    root_paths = ExperimentPaths.from_base(out_dir / experiment_id)
    root_paths.ensure()
    csv_path = root_paths.artifacts_dir / f"results_{regime}.csv"
    console.print(f"🧪 Launching grid {experiment_id} ({regime})")

    summary_rows = []
    aggregated_by_variant: Dict[str, List[Dict[str, float]]] = {}
    first_started: Optional[datetime] = None
    last_completed: Optional[datetime] = None
    statuses: List[str] = []
    total_duration = 0.0

    for expert in expert_values:
        cfg = build_scaling_config(
            regime=regime,
            d_model=d_model,
            n_heads=n_heads,
            n_layers=n_layers,
            d_ff_dense=d_ff_dense,
            e=expert,
            top_k=top_k,
            base_batch=batch_size,
            steps=max_steps,
            seq_len=seq_len,
            collect_router_stats=collect_router_stats,
        )
        cfg.eval_steps = eval_steps
        variant_label = f"experts_{expert}"
        request = ExperimentRequest(
            experiment_id=experiment_id,
            base_config=cfg,
            output_root=out_dir,
            wandb=wandb_settings,
            notes=notes,
            tags=tag,
        )

        for index in range(seeds):
            seed_value = seed + index
            replicate = index + 1 if seeds > 1 else None
            paths = request.build_run_directory(variant=variant_label, replicate=replicate)
            run_name = f"{experiment_id}-E{expert}-seed{seed_value}"
            console.print(f"• [experts={expert}] seed {seed_value} -> {paths.run_dir}")
            result = run_seed(
                request,
                seed_value=seed_value,
                wandb_settings=wandb_settings,
                paths=paths,
                run_name=run_name,
                tags=[*tag, variant_label],
                notes=notes,
                save_checkpoint=save_checkpoint,
            )

            if first_started is None:
                first_started = result.started_at
            if result.completed_at is not None:
                last_completed = result.completed_at
            statuses.append(result.status)
            total_duration += result.duration

            metrics_path = write_metrics(result.metrics, paths.artifacts_dir / "metrics.json")
            history_path = paths.artifacts_dir / "train_history.json"
            eval_history_path = paths.artifacts_dir / "eval_history.json"
            summary_path = paths.artifacts_dir / "summary_events.json"
            write_json(history_path, result.train_history)
            write_json(eval_history_path, result.eval_history)
            write_json(summary_path, result.summary_events)
            curve_path = save_training_curve(result.train_history, paths.artifacts_dir / "training_curve.png")
            reports = write_reports(paths, result.metrics, notes)

            validation_results = {
                "all_deliverables_met": result.status == "completed" and metrics_path.exists(),
                "performance_targets_met": result.metrics.get("val_loss") is not None,
                "data_integrity_checks_passed": True,
            }

            deliverable = build_deliverable_summary(
                experiment_id=f"{experiment_id}:{variant_label}",
                status=result.status,
                started_at=result.started_at,
                completed_at=result.completed_at,
                metrics=result.metrics,
                paths=paths,
                wandb_info=result.wandb_info,
                checkpoint_path=result.checkpoint_path,
                artifact_paths={
                    "metrics": metrics_path,
                    "training_curve": curve_path,
                    "train_history": history_path,
                    "eval_history": eval_history_path,
                    "summary": summary_path,
                },
                report_paths=reports,
                validation_status=validation_results,
            )
            write_json(paths.run_dir / "deliverables.json", deliverable)
            render_summary(
                console,
                experiment_id=f"{experiment_id} [{variant_label}]",
                status=result.status,
                metrics=result.metrics,
                duration=result.duration,
                artifacts={
                    "checkpoint": result.checkpoint_path,
                    "metrics": metrics_path,
                    "training_curve": curve_path,
                },
            )

            csv_row = {
                "experiment_id": experiment_id,
                "variant": variant_label,
                "seed": seed_value,
                "regime": regime,
            }
            for key, value in result.metrics.items():
                if isinstance(value, (int, float, str, bool)):
                    csv_row[key] = value
            append_row_csv(csv_path, csv_row)
            summary_rows.append(
                {
                    "variant": variant_label,
                    "seed": seed_value,
                    "started_at": result.started_at.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "completed_at": result.completed_at.strftime("%Y-%m-%dT%H:%M:%SZ") if result.completed_at else None,
                    "duration": result.duration,
                    "metrics": {
                        key: value
                        for key, value in result.metrics.items()
                        if isinstance(value, (int, float))
                    },
                }
            )
            aggregated_by_variant.setdefault(variant_label, []).append(summary_rows[-1]["metrics"])

    write_json(root_paths.run_dir / "grid_summary.json", summary_rows)

    aggregate_payload: Dict[str, Dict[str, float]] = {}
    for variant, entries in aggregated_by_variant.items():
        if not entries:
            continue
        totals: Dict[str, List[float]] = {}
        for entry in entries:
            for key, value in entry.items():
                totals.setdefault(key, []).append(value)
        aggregate_payload[variant] = {
            f"{key}_mean": statistics.mean(values) for key, values in totals.items()
        }
    write_json(root_paths.run_dir / "grid_aggregate.json", aggregate_payload)

    best_variant = None
    best_loss = float("inf")
    for variant, stats in aggregate_payload.items():
        val_loss = stats.get("val_loss_mean")
        if val_loss is not None and val_loss < best_loss:
            best_variant = variant
            best_loss = val_loss

    aggregate_metrics = {}
    if best_variant:
        agg_stats = aggregate_payload[best_variant]
        aggregate_metrics = {
            "val_loss": agg_stats.get("val_loss_mean"),
            "val_accuracy": agg_stats.get("val_accuracy_mean"),
            "tokens_per_second": agg_stats.get("tokens_per_second_mean"),
        }

    if aggregate_metrics:
        aggregate_metrics_path = write_metrics(aggregate_metrics, root_paths.artifacts_dir / "aggregate_best_metrics.json")
        reports = write_reports(root_paths, aggregate_metrics, notes)
        status = "completed" if statuses and all(s == "completed" for s in statuses) else "partial_success"
        deliverable = build_deliverable_summary(
            experiment_id=f"{experiment_id}:best",
            status=status,
            started_at=first_started or datetime.utcnow(),
            completed_at=last_completed,
            metrics=aggregate_metrics,
            paths=root_paths,
            wandb_info=None,
            checkpoint_path=None,
            artifact_paths={
                "best_metrics": aggregate_metrics_path,
                "results_csv": csv_path,
            },
            report_paths=reports,
            validation_status={
                "all_deliverables_met": status == "completed",
                "performance_targets_met": bool(aggregate_metrics),
                "data_integrity_checks_passed": True,
            },
        )
        write_json(root_paths.run_dir / "deliverables.json", deliverable)
        render_summary(
            console,
            experiment_id=f"{experiment_id} (best variant {best_variant})",
            status=status,
            metrics=aggregate_metrics,
            duration=total_duration,
            artifacts={
                "best_metrics": aggregate_metrics_path,
                "results_csv": csv_path,
            },
        )


@app.callback(invoke_without_command=True)
def main(
    ctx: Context,
    wizard: bool = typer.Option(
        True,
        "--wizard/--no-wizard",
        help="Launch the interactive Blueberry wizard when no subcommand is provided.",
    ),
) -> None:
    if ctx.invoked_subcommand is not None:
        return
    if not wizard:
        typer.echo("Interactive wizard disabled. Use `blueberry --help` for commands.")
        raise typer.Exit()
    run_wizard(console=console, run_callback=_run_from_wizard)
    raise typer.Exit()
